Repository kgu-capstone/study-with-me-fe, pull requests merged in 2023-03, with the labels that each got.

#2 [docs] PR 및 Issue 템플릿을 등록한다
  .github/ISSUE_TEMPLATE/bug-template.md
  .github/ISSUE_TEMPLATE/feature-template.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: setting

#4 [chore] 리액트 실행을 위해 기본 설정을 한다. (#3)
  package.json
Labels: bug, setting

#6 [feat] 회원가입 UI를 구현한다.
  package-lock.json
  package.json
  public/img/google_signIn.svg
  public/img/logo.svg
  public/img/profile.svg
  src/SignUp.css
  src/SignUp.jsx
  src/fonts/Pretendard-Regular.woff
Labels: feature
