Repository kgu-capstone/study-with-me-fe, pull requests merged in 2023-05, with the labels that each got.

#48 [bug] MyPage 잘못 커밋한 파일을 다시 되돌린다.
  src/css/MyPage.css
  src/pages/MyPage.jsx
Labels: bug

#49 [feat] 스터디 활동 페이지의 info영역을 서버와 연결한다.
  src/components/StudyWork/StudyInfo.jsx
Labels: feature

#52 [feat] 출석부 주차의 좌우 스크롤을 구현한다.
  src/components/StudyWork/Attend.jsx
  src/css/StudyWork.module.css
Labels: feature, style

#55 [feat] 사용자 이름을 컴포넌트화한다.
  src/components/Profile.jsx
  src/components/Report.jsx
  src/components/StudyWork/Attend.jsx
  src/components/UserName.jsx
  src/css/Nav.module.css
  src/css/Profile.module.css
  src/css/Report.module.css
  src/css/StudyWork.module.css
  src/css/UserName.module.css
Labels: feature

#63 [feat] 스터디 지원자를 보는 페이지 UI를 구현한다
  src/components/ApplicantListUserName.jsx
  src/components/StudyWork/Attend.jsx
  src/css/ApplicantList.module.css
  src/css/ApplicantListUserName.module.css
  src/css/StudyWork.module.css
  src/pages/ApplicantList.jsx
Labels: feature, style

#65 [feat] 스터디 신청자 api 연동
  src/components/ApplicantListUserName.jsx
  src/components/StudyRejectReason.jsx
  src/components/StudyWork/Attend.jsx
  src/css/ApplicantList.module.css
  src/pages/ApplicantList.jsx
Labels: feature

#67 [feat] 스터디 만들기 페이지를 등록한다.
  src/App.js
  src/components/RealEstate.js
  src/css/Main.css
  src/index.js
  src/pages/Main.jsx
  src/pages/MakeStudy.jsx
Labels: feature

#69 [feat] 스터디 만들기 기능 구현
  .yarnrc.yml
  package-lock.json
  package.json
  public/img/studyprofiles/certifacate_computerLiteracy.png
  public/img/studyprofiles/etc_teacherExam.png
  public/img/studyprofiles/interview_samsung.png
  public/img/studyprofiles/language_001.png
  public/img/studyprofiles/language_toeic.png
  public/img/studyprofiles/ncs_ncs.png
  public/img/studyprofiles/programming_baekjoon.png
  public/img/studyprofiles/thumbnailtemp.svg
  src/components/StudyProfileChoice.jsx
  src/css/Main.css
  src/css/MakeStudy.module.css
  src/css/MakeStudy.scss
  src/css/MyPage.css
  src/css/SignUp.module.css
  src/css/StudyProfileChoice.module.css
  src/css/UserName.module.css
  src/index.js
  src/pages/ApplicantList.jsx
  src/pages/MakeStudy.jsx
  src/pages/MyPage.jsx
  src/pages/SignUp.jsx
  src/pages/StudyForm.jsx
Labels: feature

#73 feat: 신고하기, 프로필보기 구현
  src/components/Profile.jsx
  src/components/Report.jsx
  src/components/StudyWork/Attend.jsx
  src/css/Profile.module.css
  src/css/Report.module.css
  src/pages/MyPage.jsx
Labels: feature, style

#74 [feat]스터디 수정 및 종료를 구현한다.
  public/img/warningbutton.png
  src/components/StudyWork/StudyInfo.jsx
  src/css/StudyRevice.module.css
  src/pages/MakeStudy.jsx
  src/pages/StudyRevice.jsx
  src/services/api.js
Labels: feature, setting, style

#75 [feat] 스터디 프로필 이미지를 등록한다.
  public/img/studyprofiles/certificate_CIP.png
  public/img/studyprofiles/certificate_CSSD.png
  public/img/studyprofiles/certificate_EIP.png
  public/img/studyprofiles/certificate_GTQ.png
  public/img/studyprofiles/certificate_KH.png
  public/img/studyprofiles/interview_LG.png
  public/img/studyprofiles/interview_NCS.png
  public/img/studyprofiles/interview_hyundai.png
  public/img/studyprofiles/language_IELTS.png
  public/img/studyprofiles/language_JLPT.png
  public/img/studyprofiles/language_JPT.png
  public/img/studyprofiles/language_Opic.png
  public/img/studyprofiles/language_TEPS.png
  public/img/studyprofiles/language_TOEFL.png
  public/img/studyprofiles/programming_C.png
  public/img/studyprofiles/programming_CSS.png
  public/img/studyprofiles/programming_HTML.png
  public/img/studyprofiles/programming_Java.png
  public/img/studyprofiles/programming_JavaScript.png
  public/img/studyprofiles/programming_Python.png
  src/components/StudyProfileChoice.jsx
  src/css/StudyProfileChoice.module.css
Labels: feature

#76 [feat] 공지사항 목록불러오기
  package-lock.json
  package.json
  public/index.html
  src/components/StudyWork/Announce.jsx
  src/css/MyPage.css
  src/css/StudyWork.module.css
  src/pages/StudyRevice.jsx
Labels: feature

#77 [feat] 댓글 등록 수정 삭제 구현 + 이미지 사이즈 + refresh Token수정 + 수정페이지onoff버튼오류수정
  public/img/participate_button.png
  public/img/setting_button.png
  src/components/StudyWork/Announce.jsx
  src/components/StudyWork/StudyInfo.jsx
  src/css/StudyWork.module.css
  src/pages/MyPage.jsx
  src/pages/StudyRevice.jsx
  src/services/api.js
Labels: bug, feature, style

#79 [feat] 공지사항 삭제 및 수정 구현 + api연동
  src/components/StudyWork/Announce.jsx
  src/components/StudyWork/Attend.jsx
  src/css/MyPage.css
  src/css/StudyWork.module.css
  src/pages/MyPage.jsx
Labels: feature

#83 [feat] 출석부 api을 연동한다.
  src/components/StudyWork/Attend.jsx
  src/components/UserName.jsx
Labels: feature

#89 [feat] 메인페이지 드롭다운 정렬 기능추가하다.
  src/components/DropDownSort.js
  src/pages/Main.jsx
Labels: feature

#92 feat: 출석률 graph, Profile, Report 일부 수정
  package-lock.json
  package.json
  src/components/Profile.jsx
  src/components/RealEstate.js
  src/components/Report.jsx
  src/css/Profile.module.css
Labels: feature, chore, style

#93 Feature/#84 메인페이지 전체적으로 기능 구현하다.
  src/SelectBOX.js
  src/components/Card.js
  src/components/Category.js
  src/components/DropDownSort.js
  src/components/RealEstate.js
  src/css/Main.css
  src/pages/Main.jsx
  src/sortManage.js
Labels: feature

#95 [feat] 메인페이지 오류 해결하다.
  package-lock.json
  package.json
  src/components/Category.js
  src/components/DropDownSort.js
  src/components/RealEstate.js
  src/pages/Main.jsx
Labels: bug

#97 [feat] PEER REVIEW 구현 + 메인페이지 스터디 불러오기 수정
  public/img/x_button.png
  src/components/DropDownSort.js
  src/components/PeerReview.jsx
  src/components/Profile.jsx
  src/components/StudyWork/Attend.jsx
  src/components/StudyWork/ByWeek.jsx
  src/css/PeerReview.module.css
  src/css/Profile.module.css
  src/css/StudyWork.module.css
  src/pages/Main.jsx
  src/pages/MakeStudy.jsx
  src/sortManage.js
Labels: bug, feature

#104 [feat] 첨부파일이름 + 주차별 리스트 UI + 팀장만 보이는 화면 + 메인, 디테일 페이지 UI + 리뷰
  public/img/email_check_false.png
  public/img/email_check_true.png
  public/img/recruit_off.png
  public/img/recruit_on.png
  public/img/study_list_line.png
  public/img/study_total_line.png
  src/components/Ad.js
  src/components/Card.js
  src/components/Category.js
  src/components/RealEstate.js
  src/components/StudyWork/Announce.jsx
  src/components/StudyWork/ByWeek.jsx
  src/components/StudyWork/StudyInfo.jsx
  src/components/StudyWork/StudySidebar.jsx
  src/css/Main.css
  src/css/SignUp.module.css
  src/css/StudyWork.module.css
  src/pages/Main.jsx
  src/pages/MakeStudy.jsx
  src/pages/MyPage.jsx
  src/pages/SignUp.jsx
  src/pages/StudyDetail.jsx
  src/pages/StudyRevice.jsx
  src/sortManage.js
Labels: feature, style

#107 [feat]무한스크롤 + 지역선택 + 로그인한 사용자
  package-lock.json
  package.json
  public/img/banner1.png
  public/img/banner2.png
  src/components/DropDownSort.js
  src/components/RealEstate.js
  src/components/StudyWork/StudyInfo.jsx
  src/css/Main.css
  src/pages/Main.jsx
  src/pages/MakeStudy.jsx
  src/pages/StudyRevice.jsx
  src/sortManage.js
Labels: feature

#113 [feat]마이페이지 완성 + 스터디리뷰 + 열정온도
  public/img/brush-2.png
  public/img/down_arrow.png
  public/img/fire.png
  public/img/frozen.png
  public/img/up_arrow.png
  src/App.js
  src/components/Profile.jsx
  src/components/RealEstate.js
  src/components/StudyReview.jsx
  src/components/StudyThumbnailChoice.jsx
  src/components/StudyWork/StudySidebar.jsx
  src/css/MakeStudy.module.css
  src/css/MyPage.css
  src/css/Profile.module.css
  src/css/ProfileRevice.module.css
  src/css/StudyReview.module.css
  src/pages/MakeStudy.jsx
  src/pages/MyPage.jsx
  src/pages/ProfileRevice.jsx
Labels: feature

#116 Feature/#114
  package-lock.json
  package.json
  src/App.js
  src/Rechart.js
  src/components/Card.js
  src/css/Main.css
  src/pages/Main.jsx
  src/pages/StudyDetail.jsx
Labels: feature

#117 [feat]열정온도 그래프 + 자잘한 버그 수정 + 프로필 활동한스터디
  package-lock.json
  public/img/thermometer_bar.png
  src/App.js
  src/components/Card.js
  src/components/GoogleLogin.jsx
  src/components/Nav.jsx
  src/components/PeerReview.jsx
  src/components/Profile.jsx
  src/css/Main.css
  src/css/MyPage.css
  src/css/Profile.module.css
  src/css/ProfileRevice.module.css
  src/pages/Main.jsx
  src/pages/MyPage.jsx
  src/pages/ProfileRevice.jsx
  src/pages/SignUp.jsx
  src/pages/StudyDetail.jsx
Labels: bug, feature

#118 [feat]사용자 정보 수정 + 자잘한 버그들 + studyId연결
  package-lock.json
  public/img/studyprofiles/certifacation_computerLiteracy.png
  public/img/studyprofiles/certification_CIP.png
  public/img/studyprofiles/certification_CSSD.png
  public/img/studyprofiles/certification_EIP.png
  public/img/studyprofiles/certification_GTQ.png
  public/img/studyprofiles/certification_KH.png
  public/index.html
  src/components/Category.js
  src/components/DropDownSort.js
  src/components/Profile.jsx
  src/components/StudyWork/Announce.jsx
  src/components/StudyWork/Attend.jsx
  src/components/StudyWork/ByWeek.jsx
  src/components/StudyWork/StudyInfo.jsx
  src/components/StudyWork/StudySidebar.jsx
  src/css/Main.css
  src/css/MakeStudy.module.css
  src/css/MyPage.css
  src/css/StudyRevice.module.css
  src/css/StudyWork.module.css
  src/pages/ApplicantList.jsx
  src/pages/Main.jsx
  src/pages/MakeStudy.jsx
  src/pages/MyPage.jsx
  src/pages/ProfileRevice.jsx
  src/pages/SignUp.jsx
  src/pages/StudyDetail.jsx
  src/pages/StudyRevice.jsx
  src/services/api.js
  src/sortManage.js
Labels: feature

#121 feat: 출석률 그래프
  src/components/Profile.jsx
  src/css/Main.css
  src/css/Profile.module.css
Labels: feature

#125 feat: 프로필, 출석률 버그 수정
  src/components/Profile.jsx
Labels: bug
