Repository kgu-capstone/study-with-me-fe, pull requests merged in 2023-06, with the labels that each got.

#130 [feat] 스터디 출석부 수정+졸업수정+팀장위임수정
  public/img/graduate.png
  src/components/Card.js
  src/components/Modal/Profile.jsx
  src/components/Modal/Report.jsx
  src/components/StudyWork/Attendances.jsx
  src/components/StudyWork/StudyInfo.jsx
  src/components/StudyWork/Weeks.jsx
  src/css/Report.module.css
  src/css/StudyWork.module.css
  src/pages/MyPage.jsx
  src/pages/StudyApplicants.jsx
  src/services/api.js
Labels: refactor

#132 [feat] 수동출석변경 + 출석 색 표시로
  src/components/AttendRevice.jsx
  src/components/Modal/PeerReview.jsx
  src/components/Modal/Profile.jsx
  src/components/Modal/StudyRejectReason.jsx
  src/components/Modal/StudyReview.jsx
  src/components/StudyWork/Attendances.jsx
  src/css/StudyWork.module.css
  src/pages/StudyApplicants.jsx
Labels: feature

#134 [bug] 스터디디테일 로그인없이 + 리뷰와 신청자보기 json넣기 + 프로필이름수정
  src/components/Modal/PeerReview.jsx
  src/components/Modal/Profile.jsx
  src/components/Modal/StudyRejectReason.jsx
  src/components/Modal/StudyReview.jsx
  src/components/StudyWork/Attendances.jsx
  src/css/PeerReview.module.css
  src/pages/StudyApplicants.jsx
  src/pages/StudyDetail.jsx
  src/services/api.js
Labels: bug

#140 feat : 메인페이지 찜
  src/App.js
  src/components/Card.js
  src/pages/Main.jsx
  src/pages/StudyDetail.jsx
Labels: feature

#142 [Infra] NCP Server 배포를 위한 Github Actions Workflows yml을 추가한다
  .github/workflows/frontend-cd.yml
Labels: deploy

#145 [feat] logout할 때 api 호출부분 추가
  public/img/studyprofiles/language_TOEIC.png
  public/img/studyprofiles/programming_Baekjoon.png
  src/components/Nav.jsx
Labels: feature

#146 [fix] logout시 api 호출 부분 추가
  public/img/studyprofiles/language_toeic.png
  public/img/studyprofiles/programming_baekjoon.png
  src/components/Nav.jsx
Labels: feature

#148 [fix] 출석부의 이름과 상태 높이가 맞도록 수정
  src/components/Nav.jsx
  src/css/StudyWork.module.css
Labels: bug

#150 [fix] 출석부 높이 및 path 마저 수정
  src/components/AttendRevice.jsx
  src/components/Nav.jsx
  src/components/StudyWork/Notices.jsx
  src/css/StudyWork.module.css
  src/services/api.js
Labels: bug

#152 [docs] 리드미 업도르
  README.md
Labels: document
