Repository kgu-capstone/study-with-me-fe, pull requests merged in 2023-04, with the labels that each got.

#11 [feat] 회원가입 페이지에서 사용자 프로필생성을 구현한다.
  package-lock.json
  package.json
  src/SignUp.jsx
Labels: feature

#12 [feat] 로그인을 구현한다.
  package-lock.json
  package.json
  public/img/close_button.svg
  src/GoogleLogin.jsx
  src/Nav.css
  src/Nav.jsx
  src/SignIn.jsx
  src/SignIn.module.css
  src/SignUp.css
  src/SignUp.jsx
  src/index.js
Labels: feature

#14 [feat] main 페이지를 등록한다.
  src/footer.jsx
  src/main.css
  src/main.jsx
Labels: feature

#16 [feat] main 페이지 디테일 css 적용한다.
  src/main.css
  src/main.jsx
Labels: feature

#18 [bug] 로그인 구현 수정 (+라우터 이용하면서 프로젝트 구조 수정)
  package-lock.json
  package.json
  public/favicon.ico
  public/logo192.png
  public/logo512.png
  src/App.css
  src/App.js
  src/Nav.css
  src/Nav.jsx
  src/SignIn.jsx
  src/components/Footer.jsx
  src/components/GoogleLogin.jsx
  src/components/Nav.jsx
  src/css/Main.css
  src/css/Nav.module.css
  src/css/SignIn.module.css
  src/css/SignUp.css
  src/index.js
  src/logo.svg
  src/pages/Main.jsx
  src/pages/MyPage.jsx
  src/pages/Root.jsx
  src/pages/SignIn.jsx
  src/pages/SignUp.jsx
Labels: bug, feature, refactor

#21 [feat]회원가입 동작을 구현한다.
  public/img/info-circle.svg
  src/components/GoogleLogin.jsx
  src/components/Nav.jsx
  src/css/SignUp.css
  src/pages/SignUp.jsx
Labels: feature

#24 [feat] 메인페이지 컴포넌트화하다.
  package-lock.json
  package.json
  public/index.html
  src/SelectBOX.js
  src/components/Ad.js
  src/components/Card.js
  src/components/Category.js
  src/components/DropDownSort.js
  src/components/Foot.js
  src/components/RealEstate.js
  src/css/Main.css
  src/index.js
  src/pages/Main.jsx
Labels: feature

#29 [feat] 스터디 세부 활동페이지 기본 UI를 구현한다.
  package.json
  public/img/announce_icon_black.svg
  public/img/announce_icon_red.svg
  public/img/attend_icon_black.svg
  public/img/attend_icon_red.svg
  public/img/byweek_icon_black.svg
  public/img/byweek_icon_red.svg
  public/img/example-image.svg
  public/img/study_profile.svg
  src/App.js
  src/components/Nav.jsx
  src/components/StudyWork/Announce.jsx
  src/components/StudyWork/Attend.jsx
  src/components/StudyWork/ByWeek.jsx
  src/components/StudyWork/StudyInfo.jsx
  src/components/StudyWork/StudySidebar.jsx
  src/css/Nav.module.css
  src/css/StudyWork.module.css
  src/fonts/Pretendard-Bold.woff
  src/pages/SignUp.jsx
  src/pages/StudyWork.jsx
Labels: feature

#30 [feat] mypage ui를 구현합니다.
  package-lock.json
  src/css/MyPage.css
  src/pages/MyPage.jsx
Labels: feature

#32 [feat] 스터디 디테일 페이지를 등록한다.
  public/img/FFFFFF.png
  public/img/favicon.png
  public/index.html
  src/App.js
  src/components/Card.js
  src/components/Nav.jsx
  src/css/Main.css
  src/pages/Main.jsx
  src/pages/StudyDetail.jsx
Labels: feature

#34 [feat] api를 모아둔 파일을 추가한다.
  src/components/GoogleLogin.jsx
  src/pages/SignUp.jsx
  src/services/api.js
Labels: feature, refactor

#36 [feat]: MyPage 사용자 정보 API를 사용한다.
  src/css/MyPage.css
  src/pages/MyPage.jsx
Labels: feature

#40 [feat] 공지사항 및 스터디의 글쓰기를 구현한다.
  .gitignore
  package-lock.json
  package.json
  src/components/GoogleLogin.jsx
  src/components/StudyWork/Announce.jsx
  src/components/StudyWork/ByWeek.jsx
  src/css/MyPage.css
  src/css/StudyWork.module.css
  src/pages/MyPage.jsx
  src/pages/SignUp.jsx
Labels: feature
